apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: speedtest-tracker
    app.kubernetes.io/instance: speedtest-tracker
    app.kubernetes.io/name: speedtest-tracker-configmap    
    app.kubernetes.io/component: configmap
  annotations:
    reloader.stakater.com/auto: "true"
  name: speedtest-tracker-configmap  
  namespace: speedtest-tracker
data:
  TZ: 'America/Los_Angeles'
  APP_TIMEZONE: 'America/Los_Angeles'
  DISPLAY_TIMEZONE: 'America/Los_Angeles'
  PUID: '1000'
  PGID: '1000'
  DB_CONNECTION: pgsql
  DB_HOST: speedtest-tracker-postgres
  DB_PORT: "postgres"
  DB_DATABASE: speedtest_tracker
  DB_USERNAME: speedy
  SPEEDTEST_SCHEDULE: "0 * * * *" # can be represented as a cron schedule same as before.
  #SPEEDTEST_SERVERS:  # you can add one or many servers separated by a comma (i.e. "123456,654321,987654").
  PRUNE_RESULTS_OLDER_THAN: "30"
  
 
