apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: speedtest-tracker
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/part-of: speedtest-tracker
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: tcp
  selector:
    app.kubernetes.io/name: speedtest-tracker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: service-account
    app.kubernetes.io/instance: speedtest-tracker
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/part-of: speedtest-tracker
  name: speedtest-tracker
  namespace: speedtest-tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: speedtest-tracker
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/part-of: speedtest-tracker
  annotations:
    reloader.stakater.com/auto: "true"
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: speedtest-tracker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: speedtest-tracker
    spec:
      # dnsPolicy: None
      # dnsConfig:
      #   nameservers:
      #     - 1.1.1.1
      #     - 127.0.0.53
      #   searches:
      #     - speedtest-tracker.svc.cluster.local
      #     - speedtest-tracker-postgres.svc.cluster.local
      #   options:
      #     - name: ndots
      #       value: "5"
      # enableServiceLinks: true
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:v0.21.2-ls44
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: speedtest-tracker-configmap
            - secretRef:
                name: speedtest-tracker-app-key
            - secretRef:
                name: postgres-secrets
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            # - name: nginx
            #   mountPath: /var/lib/nginx
            # - name: run-service
            #   mountPath: /run/service
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          # startupProbe:
          #   failureThreshold: 30
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   tcpSocket:
          #     port: 80
          #   timeoutSeconds: 1
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 384m
              memory: 384Mi
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - ALL
      #       readOnlyRootFilesystem: true
      # securityContext:
      #   fsGroup: 1000
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   seccompProfile:
      #     type: RuntimeDefault
      serviceAccount: speedtest-tracker
      serviceAccountName: speedtest-tracker
      volumes:
        - name: config
          emptyDir:
            {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
