apiVersion: v1
kind: Service
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/part-of: speedtest-tracker
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: speedtest-tracker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: speedtest-tracker
    app.kubernetes.io/part-of: speedtest-tracker
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: speedtest-tracker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: speedtest-tracker
    spec:
      # dnsPolicy: None
      # dnsConfig:
      #   nameservers:
      #     - 1.1.1.1
      #     - 127.0.0.53
      #   searches:
      #     - speedtest-tracker.svc.cluster.local
      #     - speedtest-tracker-postgres.svc.cluster.local
      #   options:
      #     - name: ndots
      #       value: "5"
      # enableServiceLinks: true
      containers:
        - name: speedtest-tracker
          image: lscr.io/linuxserver/speedtest-tracker:v0.19.0-ls20
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: speedtest-tracker-configmap
            - secretRef:
                name: postgres-secrets
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            # - name: nginx
            #   mountPath: /var/lib/nginx
            # - name: run-service
            #   mountPath: /run/service
          # livenessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 0
          #   periodSeconds: 10
          #   tcpSocket:
          #     port: 8080
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 3
          #   initialDelaySeconds: 0
          #   periodSeconds: 10
          #   tcpSocket:
          #     port: 8080
          #   timeoutSeconds: 1
          # startupProbe:
          #   failureThreshold: 30
          #   initialDelaySeconds: 0
          #   periodSeconds: 5
          #   tcpSocket:
          #     port: 8080
          #   timeoutSeconds: 1
          resources:
            requests:
              cpu: 128m
              memory: 128Mi
            limits:
              cpu: 384m
              memory: 384Mi
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - ALL
      #       readOnlyRootFilesystem: true
      # securityContext:
      #   fsGroup: 65533
        # runAsUser: 65533
        #runAsGroup: 65533
      #   seccompProfile:
      #     type: RuntimeDefault
      volumes:
        - name: config
          emptyDir:
            {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
