---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: speedtest-tracker
spec:
  encryptedData:
    DB_PASSWORD: AgB8jbA0rrp5dKs3bJQvrYvPzYGGXlzX8zmgGDz1DxkxGY+HmIWkWodHBbaCqnbyu1LSNaLyuqtiADSg1aG5saFHW2HcNMTSgMJbbN68ZW6leHumhgidoY8fbyDsvD5g7++BKApp01MeROM8ocl1Gf6sCzWsiIqgML7NVUXpxVrwJSaf3nBoGqVd0zeqzfNmVj91VAGtIYUx60BBMXoZgyk6FndqdhOtpbGdDcJ5KL8VMEiPtBmlgXRZiOjEG/kebmo8yQEDgmB2+EDr0oxJw8wBvpscBQ+rah1656Tu6/Kpsh8H3PtaQQMg2ZfRu77Y1Ppz3CDDsfRuP5/Hcm5fdKGIUDY5DNVkf1J2QxWOuErVytg7MOgLHWv6PVZ7ZLhJniFKyr+9nRo1hOaELgepc8xeYifh5sg9XKwRZ+41/EfYE6hYklVFywBIUS1buUCDTmaOlDeRd5fULsnSk3fduxKL6Z3DXE4nPmd0+ES84XA2gZVYAdZIGi+3SeoA4BI+ZcVircLYp3Hi7qigCdqav/CEp+fB6VNxA+Vg3J7+QT7G1RfE3E0K5BUY1FN3cn/uCqbzTiT/Gd++LdVpTDsSAaO9RuFhyaaNt2t36l23z8Tq+RTavMI1X2sJcM41piRUcmQOeS6PYpx1htz8SBVeL1yl6jGl936/VvR1AtLV4JUM5m79KoxnD6eZi1JWA6cr2VPWfxWoKxp3pSDyIw==
    POSTGRES_PASSWORD: AgCmr8HDeOJTQtFjdBgMi4KBO/I3y5Ishnalzp+W3oBkU3rC8a0HINRIy2zSJzh8KI9FH1vHqSseiHXIcKXt1FOW9NLlx7Az7MPItJxnAGptkf5hWiCBgnWXRqIi5SUhN7AFZdVeUHr4nU/IPFUA2A/ycrBQAWZppqo3nP6UCSIWfHm2Qsr9ThR3UF8pA6JfSMslJUf+de3tQujsNNnEUaRI8ghqXiERQh07wAOCpD9G80sugy/jouOxR4pTZxk5p5L5s6X8yYylU6S0sOXvUdpQz509hJp3vFI+vpExH1sSuZP2+AUXzUwXY3DvuNxGSWwn539N8/f9krXZ5gprsWn8+kviB1VFWFyAMnCPaiVyd+qKyLWsdX2/dEIYYK347LIMq8yyt9H8Y3CLHu/11gOehRaHwJmAmVnPXg9MqwsdUJUx3LEpn2A51mZMS5U6GGx8F44cMdXzhyoiMJhqadn22JSXI1WekQb9pvYLfphCf8itqrjZYlDVttjwBIhRDNjrzW9G/PS99Qx3NqJe+sA/Ly3irN+mkfHk4wuUmZ2r6RohqGnl0FOJQsFTTt2J19DGrpnukI2vkNLq+jBN2AITlkwXvv4w0lEKmBW6ztpzPcpR500/qUD2wlt0kiRBoSGBADM4F259f+N5j+W0LOQ3ObK3T8iGU+JS277THWPvERUDtsK3dIiDDukublNfLrIYv3PKGy8+Zfllkw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: speedtest-tracker
    type: Opaque
