---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: speedtest-tracker-postgres
    app.kubernetes.io/part-of: speedtest-tracker
    app.kubernetes.io/component: database
  name: speedtest-tracker-postgres
  namespace: speedtest-tracker
spec:
  selector:
    app.kubernetes.io/name: speedtest-tracker-postgres
  ports:
  - protocol: TCP
    name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: speedtest-tracker-postgres
    app.kubernetes.io/part-of: speedtest-tracker
    app.kubernetes.io/component: database
  name: speedtest-tracker-postgres  
  namespace: speedtest-tracker
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: speedtest-tracker-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: speedtest-tracker-postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gaptech.com/environment-stage
                operator: Exists
      containers:
        - name: postgres
          image: postgres:16.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432  
          securityContext:
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          envFrom:
            - configMapRef:
                name: speedtest-tracker-postgres-config
            - secretRef:
                name: postgres-secrets
          volumeMounts:
            - name: speedtest-tracker-postgredb
              mountPath: /var/lib/postgresql
              subPath: data
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run/postgresql/  
      volumes:
        - name: speedtest-tracker-postgredb
          persistentVolumeClaim:
            claimName: speedtest-tracker-postgres-claim
        - name: tmp
          emptyDir: {} 
        - name: run
          emptyDir: {}       
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: speedtest-tracker-postgres-claim  
  namespace: speedtest-tracker
  labels:
    app: speedtest-tracker-postgres
    app.kubernetes.io/part-of: speedtest-tracker
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 5Gi  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-tracker-postgres-config
  namespace: speedtest-tracker
  labels:
    app: speedtest-tracker-postgres
    app.kubernetes.io/part-of: speedtest-tracker
    app.kubernetes.io/component: database
data:
  POSTGRES_DB: speedtest_tracker
  POSTGRES_HOST: speedtest-tracker-postgres
  POSTGRES_PORT: "5432"
  PGDATA: /var/lib/postgresql/data
  LOG_LEVEL: debug
